<?php

/**
 * BaseAlbumsUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_album
 * @property integer $id_user
 * @property Album $Album
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getIdAlbum()     Returns the current record's "id_album" value
 * @method integer     getIdUser()      Returns the current record's "id_user" value
 * @method Album       getAlbum()       Returns the current record's "Album" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method AlbumsUsers setIdAlbum()     Sets the current record's "id_album" value
 * @method AlbumsUsers setIdUser()      Sets the current record's "id_user" value
 * @method AlbumsUsers setAlbum()       Sets the current record's "Album" value
 * @method AlbumsUsers setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    sonor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlbumsUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('albums_users');
        $this->hasColumn('id_album', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_user', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Album', array(
             'local' => 'id_album',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'id_user',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}