<?php

/**
 * BaseChansonsPlaylists
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_playlist
 * @property integer $id_chanson
 * @property Playlist $Playlist
 * @property Chanson $Chanson
 * 
 * @method integer           getIdPlaylist()  Returns the current record's "id_playlist" value
 * @method integer           getIdChanson()   Returns the current record's "id_chanson" value
 * @method Playlist          getPlaylist()    Returns the current record's "Playlist" value
 * @method Chanson           getChanson()     Returns the current record's "Chanson" value
 * @method ChansonsPlaylists setIdPlaylist()  Sets the current record's "id_playlist" value
 * @method ChansonsPlaylists setIdChanson()   Sets the current record's "id_chanson" value
 * @method ChansonsPlaylists setPlaylist()    Sets the current record's "Playlist" value
 * @method ChansonsPlaylists setChanson()     Sets the current record's "Chanson" value
 * 
 * @package    sonor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChansonsPlaylists extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chansons_playlists');
        $this->hasColumn('id_playlist', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_chanson', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Playlist', array(
             'local' => 'id_playlist',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Chanson', array(
             'local' => 'id_chanson',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}