get_artiste:
  url: /admin/recherche-artiste
  param: { module: artiste, action: search }
  
get_album:
  url: /admin/recherche-album
  param: { module: album, action: search }

chanson_no_metadata:
  class: sfDoctrineRouteCollection
  options:
    model:                Chanson
    module:               no_metadata
    prefix_path:          /admin/chansons-sans-metadonnees
    column:               id
    with_wildcard_routes: true

playlist:
  class: sfDoctrineRouteCollection
  options:
    model:                Playlist
    module:               playlist
    prefix_path:          /admin/playlists
    column:               id
    with_wildcard_routes: true

chanson:
  class: sfDoctrineRouteCollection
  options:
    model:                Chanson
    module:               chanson
    prefix_path:          /admin/chansons
    column:               id
    with_wildcard_routes: true

album:
  class: sfDoctrineRouteCollection
  options:
    model:                Album
    module:               album
    prefix_path:          /admin/albums
    column:               id
    with_wildcard_routes: true

artiste:
  class: sfDoctrineRouteCollection
  options:
    model:                Artiste
    module:               artiste
    prefix_path:          /admin/artistes
    column:               id
    with_wildcard_routes: true

homepage:
  url:   /admin/
  param: { module: no_metadata, action: index }