get_artiste:
  url: /recherche-artiste
  param: { module: artiste, action: search }
  
get_album:
  url: /recherche-album
  param: { module: album, action: search }

chanson_no_metadata:
  class: sfDoctrineRouteCollection
  options:
    model:                Chanson
    module:               no_metadata
    prefix_path:          /no_metadata
    column:               id
    with_wildcard_routes: true

playlist:
  class: sfDoctrineRouteCollection
  options:
    model:                Playlist
    module:               playlist
    prefix_path:          /playlist
    column:               id
    with_wildcard_routes: true

chanson:
  class: sfDoctrineRouteCollection
  options:
    model:                Chanson
    module:               chanson
    prefix_path:          /chanson
    column:               id
    with_wildcard_routes: true

album:
  class: sfDoctrineRouteCollection
  options:
    model:                Album
    module:               album
    prefix_path:          /album
    column:               id
    with_wildcard_routes: true

artiste:
  class: sfDoctrineRouteCollection
  options:
    model:                Artiste
    module:               artiste
    prefix_path:          /artiste
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
