generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Chanson
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          chanson_no_metadata
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        id_album: { label: Album }
        new_album: { label: Nouvel Album }
      list:    
        display: [titre, duree, Album]
        table_method: retrieveNoMedatada
        max_per_page: 10
        actions: {}
      filter:  
        display: [titre, id_album]
      form:    
        class: ChansonNoMetadataForm
      edit:    
        display:
          "NONE": [titre, piste, has_metadata, duree, audio_file]
          "Sélection de l'album": [id_album, new_album]
      new:     ~
