<?php

/**
 * Album
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sonor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Album extends BaseAlbum
{
  public function __toString()
  {
    return (($this->titre != '') ? $this->titre : '');
  }
  
  public function getArtisteDirectory() 
  {
    return $this->Artiste->slug."/";
  }
  
  public static function issetOrCreate($album, $artiste_id)
  {
    if(!is_null($album) && ($alb = Doctrine_Core::getTable('Album')->findOneBy('titre', $album)) !== false)
    {
      return $alb->id;
    }
    $alb = new Album();
    $alb->titre = $album;
    $alb->id_artiste = $artiste_id;
    $alb->save();
    return $alb->id;
  }
}
