<?php

/**
 * AlbumsUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumsUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumsUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AlbumsUsers');
    }
    
  public function remove($album_id, $user_id) 
  {
    $dq = self::createQuery('au')
          ->delete()
          ->where('au.id_album=?', $album_id)
          ->andWhere('au.id_user=?', $user_id);
    return $dq->execute();
  }
}