<?php

/**
 * AlbumsUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumsUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumsUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AlbumsUsers');
    }
}