<?php

/**
 * AlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Album');
    }

  public function getAlbumsFormUser($user_id)
  {
    $dq = self::createQuery('a')
          ->select('a.*')
          ->whereIn('u.id', array($user_id))
          ->leftJoin('a.Users u')
          ->orderBy('a.titre ASC');
    return $dq->execute();
  }

  public function getAutocompletion($q, $limit)
  {
    $dq = self::createQuery()
            ->select("id, titre")
            ->where("titre LIKE ?","%".$q."%")
            ->limit($limit);
    return $dq->execute(array(), Doctrine::HYDRATE_ARRAY);
  }
  
  public function searchEverything($q, $limit = 10) 
  {
    $dq = self::createQuery('a')
          ->select("a.*")
          ->where("a.titre LIKE ?","%".$q."%")
          ->limit($limit)
          ->orderBy('a.titre ASC');
    return $dq->execute();
  }
}