<?php

/**
 * Artiste
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sonor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Artiste extends BaseArtiste
{
  public function __toString()
  {
    return (($this->nom != '') ? $this->nom : '');
  }
  
  public static function issetOrCreate($artiste)
  {
    if(!is_null($artiste) && ($art = Doctrine_Core::getTable('Artiste')->findOneBy('nom', $artiste)) !== false)
    {
      return $art->id;
    }
    $art = new Artiste();
    $art->nom = $artiste;
    $art->save();
    return $art->id;
  }
}
