<?php

/**
 * ArtisteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArtisteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArtisteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Artiste');
    }

  public function getAutocompletion($q, $limit)
  {
    $dq = self::createQuery()
            ->select("id, nom")
            ->where("nom LIKE ?","%".$q."%")
            ->limit($limit);
    return $dq->execute(array(), Doctrine::HYDRATE_ARRAY);
  }
}