<?php

/**
 * Chanson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sonor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Chanson extends BaseChanson
{
  public function __toString()
  {
    return $this->titre;
  }  
  
  public function generateAudioFileFilename(sfValidatedFile $file)
  {
    return tools::slugify($this->getAudioFilenameWithoutExtension($file)).$file->getOriginalExtension();
  }
  
  public function getAudioFilenameWithoutExtension(sfValidatedFile $file) 
  {
    return substr($file->getOriginalName(), 0, (strlen($file->getOriginalName()) - strlen($file->getOriginalExtension())));
  }
}
