<?php

/**
 * ChansonsPlaylistsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChansonsPlaylistsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChansonsPlaylistsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChansonsPlaylists');
    }
}