<?php

/**
 * Playlist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sonor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Playlist extends BasePlaylist
{
  public function __toString()
  {
    return $this->titre;
  }
  
  public function countChansons() 
  {
    return count($this->getChansons());
  }
}
