<?php

/**
 * PlaylistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaylistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlaylistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Playlist');
    }

  public function getPlaylistsFormUser($user_id)
  {
    $dq = self::createQuery('p')
//          ->select('p.*, c.*, COUNT(c.id) as count')
          ->select('p.*, c.*')
          ->where('p.id_user = ?', $user_id)
          ->leftJoin('p.Chansons c')
//          ->having('count > 0')
          ->orderBy('p.titre ASC');
    return $dq->execute();
  }
}