search:
  url:  /recherche/:type
  param:  { module: accueil, action: search, type: '' }
  
play:
  url:  /lecture/:type/:slug
  param:  { module: accueil, action: ajaxLecture, type: chanson, slug: '' }

show_chansons:
  url:  /liste-des-chansons/:type/:slug
  param:  { module: accueil, action: ajaxListeChansons, type: '', slug: '' }

get_album_field:
  url:  /champ-album
  param:  { module: accueil, action: ajaxGetChampAlbumField }

remove:
  url:  /suppression/:type/:slug
  param:  { module: accueil, action: ajaxRemove, type: '', slug: '' }

add:
  url:  /ajout/:type/:titre
  param:  { module: accueil, action: ajaxAdd, type: '', titre: '' }

javascript_functions:
  url:   /functions.:sf_format
  param: { module: accueil, action: javascript, sf_format: js }

homepage:
  url:   /
  param: { module: accueil, action: index }