get_chanson:
  url: /lecture-de-la-chanson/:slug
  param:  { module: accueil, action: getChanson, slug: '' }

play:
  url:  /lecture/:type/:slug
  param:  { module: accueil, action: ajaxLecture, type: '', slug: '' }

show_chansons:
  url:  /liste-des-chansons/:type/:slug
  param:  { module: accueil, action: ajaxListeChansons, type: '', slug: '' }

javascript_functions:
  url:   /functions.:sf_format
  param: { module: accueil, action: javascript, sf_format: js }
#  requirements:
#    sf_format: (?:js)

homepage:
  url:   /
  param: { module: accueil, action: index }