# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Sonor project
    #description:  symfony project
    #keywords:     symfony, project
    language:     fr
    #robots:       index, follow

  stylesheets:    [main.css, /sfFormExtraPlugin/css/jquery.autocompleter.css, jquery/jquery.alerts.css, jquery/notification.css, jquery/jquery-ui.custom.css]

  javascripts:    [jquery/jquery.min.js, jquery/jquery-ui.custom.min.js]

  has_layout:     true
  layout:         layout
