# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Sonor project
    #description:  symfony project
    #keywords:     symfony, project
    language:     fr
    #robots:       index, follow

  stylesheets:    [main.css, frontend.css]

  javascripts:    [/js/jquery/jquery.min.js, /js/jquery/jquery-ui.custom.min.js, /sfFormExtraPlugin/js/jquery.autocompleter.js, /js/audio_player.js]

  has_layout:     true
  layout:         layout
