all:
  files_storage_path: 
    mp3: <?php echo sfConfig::get('sf_upload_dir') ?>/audio/mp3/
    ogg: <?php echo sfConfig::get('sf_upload_dir') ?>/audio/ogg/
    todo: <?php echo sfConfig::get('sf_upload_dir') ?>/audio/todo/
    no_metadata: <?php echo sfConfig::get('sf_upload_dir') ?>/audio/no_metadata/
